function arifmetics () {
    const a = 5;
    let b = 12;
    const c = 1;
    let d = 4;
    const e = "String";
    console.log(a, b, c, d);
    b = a + d;
    console.log("b", b);
    d = c + e;
    console.log("d", d);
    d = a;
    b = d - c;
    console.log("b", b, "d", d);
    b = b**d;
    console.log("b", b);
    const booleanB1 = true;
    let booleanB2 = false;
    booleanB2 = b;
    console.log(booleanB1, booleanB2);
    b = b%c;
    console.log("b", b);
    b = d/c;
    console.log("b", b);
    d += a;
    b -= c;
    console.log("b", b, "d", d);
    d /= a;
    b *= c;
    console.log("b", b, "d", d);
}
arifmetics();
